El Bloque try se ejecuta tal cual, hasta que un posible error se ha detectado.

Si no se detecta un error durante la ejecución del bloque try, el catch se deja del lado y no se realiza.
En caso que sí se detecte un error en el bloque try, se ejecuta las sentencias que teníamos en el catch.


